name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build --build-arg GH_PAT=${{ secrets.GH_PAT }} -t playground/hello-world:latest .
