name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build, tag, and push docker image to ECR
        run: |
          docker build -t playground/hello-world:latest .
